### ISSUE TITLE
Coverage map report

### ISSUE THREAD

**Issue by stanislav-poliakov** [dropseed/pullapprove#26]
It is an idea how to analyze repository codes.

e.g. PA config has pack of rules. Some rules is related to files in repository.

User wants to get report how rules covers repository files to better adjusting.
One option is add tab `Coverage` on `https://app.pullapprove.com/report/` (where is `Group/Config/Debug`).
Another option is to allow user send command `/pullapprove-coverage` and PA sends report in next PR comment (as link or text):

e.g.
```
rule: `RuleName`
    - maybe some statistical data
    - paths or/and files
...

uncovered: 
    - maybe some statistical data
    - path or/and files
    
+ it could be space map chart to demonstrate :)

**Comment by davegaeddert** [comment]
Hey @stanislav-poliakov -- thanks for the issue. I do think this is something some people would use (especially when checking for 100% file-based coverage) and I'll keep it in mind!
