### ISSUE TITLE
GitHub workflow action is failing when creating an issue about unavailability

### ISSUE THREAD

**Issue by dmsimard-petal** [dropseed/pullapprove#61]
Hi there pullapprove,

We have a github workflow to manage availability that is identical to the one from the [documentation](https://docs.pullapprove.com/config/availability/#updating-a-file-in-a-repo).

When creating an issue about availability like this one:
![Screen Shot 2022-07-21 at 11 44 33 AM](https://user-images.githubusercontent.com/107067188/180257237-bdc7f7d9-6977-410d-9863-9bb290413170.png)

The github action fails with the following error:
![Screen Shot 2022-07-21 at 11 48 31 AM](https://user-images.githubusercontent.com/107067188/180257686-864b772b-d79f-434e-aa30-7466f3c52f55.png)

I would share links but unfortunately it's in a private repository.

Is this an issue you have seen before ? I could be mistaken but at first glance it looks like the issue title is formatted properly.

Thank you !

**Comment by davegaeddert** [comment]
Would be helpful if it logged some more info! My guess is that there is another open issue on the repo that doesn't match the format? Looks like it parsed that one correctly, but then threw an error while looking at one of the others.

**Comment by davegaeddert** [comment]
I'm going to close this for now — let me know if you have other issues!
