### ISSUE TITLE
Error: given usernames could not be requested

### ISSUE THREAD

**Issue by woody-apple** [dropseed/pullapprove#77]
For this PR: https://github.com/project-chip/matter.js/pull/458

We're seeing this failure: https://app.pullapprove.com/report/?url=https%3A//pullapprove-storage-production.s3.amazonaws.com/reports/344d1c91-72a4-48b2-8ae2-fca66b035835.json&fingerprint=9eade9e32732dd0e3f3d1ddca473b162

What's odd, is the same set worked earlier? 
I checked permissions for the team, and they do seem to be correct (no changes for a while)

<img width="906" alt="Screenshot 2023-10-30 at 2 50 26 PM" src="https://github.com/dropseed/pullapprove/assets/54152665/51e80f51-b153-4891-8f28-5f7081abd510">

**Comment by davegaeddert** [comment]
Hey @woody-apple — sorry this got buried for a couple days. On that PR, can you click the "reviewers" dropdown and see if any of these people _don't_ show up in that list?
![CleanShot 2023-11-02 at 14 44 15](https://github.com/dropseed/pullapprove/assets/649496/6d6a01cd-3fce-4c95-8614-ea88dbbaf022)

**Comment by davegaeddert** [comment]
Is it supposed to be `Wes` with a "w", or `vves` with two "v"? Or are the both involved in the project? In your screenshot it looks like the username is actually `vves`.
https://github.com/wes
https://github.com/vves

**Comment by Apollon77** [comment]
hey, Ohh right that shpuld be vves ... but in fac the issue happens with "Apollon77" right now. and the urrent list we talk about is

https://github.com/project-chip/matter.js/blob/main/.pullapprove.yml#L93-L95

**Comment by Apollon77** [comment]
Ok I fixed "vves" as user now ... I will try another PR later to see if it works now

**Comment by Apollon77** [comment]
A completely fresh PR really looks good ... seems that it was really user "Wes" which had no role in repo (because typo) and so screwed it up and not my account :-)

**Comment by davegaeddert** [comment]
👍 sounds good, glad it's fixed!
